

all:
	g++ Question1.cpp -o Question1
	g++ question2.cpp -o question2
	g++ question3.cpp -o question3
	g++ question4.cpp -o question4
	g++ question5.cpp -o question5
	g++ question6.cpp -o question6
	g++ question7.cpp -o question7

clean:
	rm -f Question1 question2 question3 question4 question5 question6 question7
